import { CountryEntry, DayEntry, StateSymbolEntry, generateWorldGK, generateImportantDays, generateStateSymbols } from './question-generator';
import { GSQuestion } from './gs-bank';

// ─── 120 Countries / Capitals / Currencies ───────────────────────────────────
export const COUNTRY_DATA: CountryEntry[] = [
  { country: 'भारत',          capital: 'नई दिल्ली',    currency: 'रुपया' },
  { country: 'चीन',           capital: 'बीजिंग',       currency: 'युआन' },
  { country: 'अमेरिका',       capital: 'वाशिंगटन DC',  currency: 'डॉलर' },
  { country: 'रूस',           capital: 'मॉस्को',       currency: 'रूबल' },
  { country: 'जापान',         capital: 'टोक्यो',       currency: 'येन' },
  { country: 'ब्रिटेन',       capital: 'लंदन',         currency: 'पाउंड' },
  { country: 'फ्रांस',        capital: 'पेरिस',        currency: 'यूरो' },
  { country: 'जर्मनी',        capital: 'बर्लिन',       currency: 'यूरो' },
  { country: 'इटली',          capital: 'रोम',          currency: 'यूरो' },
  { country: 'स्पेन',         capital: 'मैड्रिड',      currency: 'यूरो' },
  { country: 'कनाडा',         capital: 'ओटावा',        currency: 'कनाडाई डॉलर' },
  { country: 'ऑस्ट्रेलिया',   capital: 'कैनबरा',       currency: 'ऑस्ट्रेलियाई डॉलर' },
  { country: 'ब्राजील',       capital: 'ब्राजीलिया',   currency: 'रियल' },
  { country: 'अर्जेंटीना',    capital: 'ब्यूनस आयर्स', currency: 'पेसो' },
  { country: 'मेक्सिको',      capital: 'मेक्सिको सिटी', currency: 'पेसो' },
  { country: 'दक्षिण अफ्रीका', capital: 'प्रिटोरिया',  currency: 'रैंड' },
  { country: 'नाइजीरिया',     capital: 'अबुजा',        currency: 'नाइरा' },
  { country: 'मिस्र',         capital: 'काहिरा',       currency: 'मिस्री पाउंड' },
  { country: 'केन्या',        capital: 'नैरोबी',       currency: 'शिलिंग' },
  { country: 'घाना',          capital: 'अकरा',         currency: 'सेडी' },
  { country: 'पाकिस्तान',     capital: 'इस्लामाबाद',  currency: 'रुपया' },
  { country: 'बांग्लादेश',    capital: 'ढाका',         currency: 'टका' },
  { country: 'श्रीलंका',      capital: 'कोलंबो',       currency: 'रुपया' },
  { country: 'नेपाल',         capital: 'काठमांडू',     currency: 'रुपया' },
  { country: 'भूटान',         capital: 'थिम्पू',       currency: 'न्गुल्त्रम' },
  { country: 'म्यांमार',      capital: 'नेपीडो',       currency: 'क्यात' },
  { country: 'थाईलैंड',       capital: 'बैंकॉक',       currency: 'बाहत' },
  { country: 'वियतनाम',       capital: 'हनोई',         currency: 'डोंग' },
  { country: 'इंडोनेशिया',    capital: 'जकार्ता',      currency: 'रुपिया' },
  { country: 'मलेशिया',       capital: 'कुआलालंपुर',   currency: 'रिंगिट' },
  { country: 'फिलीपींस',      capital: 'मनीला',        currency: 'पेसो' },
  { country: 'सिंगापुर',      capital: 'सिंगापुर',     currency: 'सिंगापुर डॉलर' },
  { country: 'दक्षिण कोरिया', capital: 'सियोल',        currency: 'वोन' },
  { country: 'उत्तर कोरिया',  capital: 'प्योंगयांग',   currency: 'वोन' },
  { country: 'ईरान',          capital: 'तेहरान',       currency: 'रियाल' },
  { country: 'इराक',          capital: 'बगदाद',        currency: 'दीनार' },
  { country: 'सऊदी अरब',      capital: 'रियाध',        currency: 'रियाल' },
  { country: 'संयुक्त अरब अमीरात', capital: 'अबू धाबी', currency: 'दिरहम' },
  { country: 'इज़राइल',       capital: 'जेरूसलम',      currency: 'शेकेल' },
  { country: 'तुर्की',        capital: 'अंकारा',       currency: 'लीरा' },
  { country: 'यूक्रेन',       capital: 'कीव',          currency: 'रिव्निया' },
  { country: 'पोलैंड',        capital: 'वारसा',        currency: 'ज़लॉटी' },
  { country: 'स्वीडन',        capital: 'स्टॉकहोम',     currency: 'क्रोना' },
  { country: 'नॉर्वे',        capital: 'ओस्लो',        currency: 'क्रोन' },
  { country: 'डेनमार्क',      capital: 'कोपेनहेगन',    currency: 'क्रोन' },
  { country: 'फिनलैंड',       capital: 'हेलसिंकी',     currency: 'यूरो' },
  { country: 'स्विट्जरलैंड',  capital: 'बर्न',         currency: 'फ्रैंक' },
  { country: 'ऑस्ट्रिया',     capital: 'वियना',        currency: 'यूरो' },
  { country: 'बेल्जियम',      capital: 'ब्रसेल्स',     currency: 'यूरो' },
  { country: 'नीदरलैंड',      capital: 'एम्स्टर्डम',   currency: 'यूरो' },
  { country: 'पुर्तगाल',      capital: 'लिस्बन',       currency: 'यूरो' },
  { country: 'ग्रीस',         capital: 'एथेंस',        currency: 'यूरो' },
  { country: 'न्यूजीलैंड',    capital: 'वेलिंगटन',     currency: 'न्यूजीलैंड डॉलर' },
  { country: 'क्यूबा',        capital: 'हवाना',        currency: 'पेसो' },
  { country: 'वेनेजुएला',     capital: 'काराकस',       currency: 'बोलिवर' },
  { country: 'कोलंबिया',      capital: 'बोगोटा',       currency: 'पेसो' },
  { country: 'चिली',          capital: 'सैंटियागो',    currency: 'पेसो' },
  { country: 'पेरू',          capital: 'लीमा',         currency: 'सोल' },
  { country: 'इथियोपिया',     capital: 'अदीस अबाबा',   currency: 'बिर्र' },
  { country: 'तंजानिया',      capital: 'डोडोमा',       currency: 'शिलिंग' },
  { country: 'युगांडा',       capital: 'कंपाला',       currency: 'शिलिंग' },
  { country: 'जिम्बाब्वे',    capital: 'हरारे',        currency: 'डॉलर' },
  { country: 'मोरक्को',       capital: 'रबात',         currency: 'दिरहम' },
  { country: 'अल्जीरिया',     capital: 'अल्जीयर्स',    currency: 'दीनार' },
  { country: 'ट्यूनीशिया',    capital: 'ट्यूनिस',      currency: 'दीनार' },
  { country: 'लीबिया',        capital: 'त्रिपोली',     currency: 'दीनार' },
  { country: 'सूडान',         capital: 'खार्तूम',      currency: 'पाउंड' },
  { country: 'अफगानिस्तान',   capital: 'काबुल',        currency: 'अफगानी' },
  { country: 'उज्बेकिस्तान',  capital: 'ताशकंद',       currency: 'सोम' },
  { country: 'कजाकिस्तान',    capital: 'अस्ताना',      currency: 'टेंगे' },
  { country: 'मंगोलिया',      capital: 'उलानबाटर',     currency: 'तोग्रोग' },
  { country: 'कंबोडिया',      capital: 'नोम पेन्ह',    currency: 'रिएल' },
  { country: 'श्रीलंका',      capital: 'श्री जयवर्धनेपुरा', currency: 'रुपया' },
  { country: 'मालदीव',        capital: 'माले',         currency: 'रुफिया' },
  { country: 'म्यांमार',      capital: 'नेपीडो',       currency: 'क्यात' },
  { country: 'लाओस',          capital: 'वियनतियाने',   currency: 'किप' },
  { country: 'ब्रुनेई',       capital: 'बंदर सेरी बेगावान', currency: 'डॉलर' },
  { country: 'ओमान',          capital: 'मस्कट',        currency: 'रियाल' },
  { country: 'कुवैत',         capital: 'कुवैत सिटी',   currency: 'दीनार' },
  { country: 'बहरीन',         capital: 'मनामा',        currency: 'दीनार' },
  { country: 'कतर',           capital: 'दोहा',         currency: 'रियाल' },
  { country: 'यमन',           capital: 'सना',          currency: 'रियाल' },
  { country: 'जॉर्डन',        capital: 'अम्मान',       currency: 'दीनार' },
  { country: 'लेबनान',        capital: 'बेरूत',        currency: 'पाउंड' },
  { country: 'सीरिया',        capital: 'दमिश्क',       currency: 'पाउंड' },
  { country: 'साइप्रस',       capital: 'निकोसिया',     currency: 'यूरो' },
  { country: 'अज़रबैजान',     capital: 'बाकू',         currency: 'मनात' },
  { country: 'जॉर्जिया',      capital: 'त्बिलिसी',    currency: 'लारी' },
  { country: 'आर्मेनिया',     capital: 'येरेवान',      currency: 'द्राम' },
  { country: 'हंगरी',         capital: 'बुडापेस्ट',    currency: 'फोरिंट' },
  { country: 'चेक गणराज्य',   capital: 'प्राग',        currency: 'कोरुना' },
  { country: 'रोमानिया',      capital: 'बुखारेस्ट',    currency: 'लेउ' },
  { country: 'बुल्गारिया',    capital: 'सोफिया',       currency: 'लेव' },
  { country: 'क्रोएशिया',     capital: 'जाग्रेब',      currency: 'यूरो' },
  { country: 'सर्बिया',       capital: 'बेलग्रेड',     currency: 'दीनार' },
  { country: 'स्लोवाकिया',    capital: 'ब्राटिस्लावा',  currency: 'यूरो' },
  { country: 'आयरलैंड',       capital: 'डबलिन',        currency: 'यूरो' },
  { country: 'लक्जमबर्ग',     capital: 'लक्जमबर्ग',    currency: 'यूरो' },
  { country: 'माल्टा',        capital: 'वालेटा',       currency: 'यूरो' },
  { country: 'आइसलैंड',       capital: 'रेकजाविक',     currency: 'क्रोना' },
  { country: 'जमैका',         capital: 'किंग्स्टन',    currency: 'डॉलर' },
  { country: 'त्रिनिदाद',     capital: 'पोर्ट ऑफ स्पेन', currency: 'डॉलर' },
  { country: 'पनामा',         capital: 'पनामा सिटी',   currency: 'बालबोआ' },
  { country: 'कोस्टारिका',    capital: 'सान होसे',     currency: 'कोलोन' },
  { country: 'होंडुरास',      capital: 'तेगुसिगाल्पा',  currency: 'लेम्पिरा' },
  { country: 'ग्वाटेमाला',    capital: 'ग्वाटेमाला सिटी', currency: 'क्वेटज़ल' },
  { country: 'बोलीविया',      capital: 'सुक्रे',       currency: 'बोलिवियानो' },
  { country: 'पैराग्वे',      capital: 'असुनसियोन',    currency: 'गुआरानी' },
  { country: 'उरुग्वे',       capital: 'मोंटेवीडियो',  currency: 'पेसो' },
  { country: 'एक्वाडोर',      capital: 'क्विटो',       currency: 'डॉलर' },
  { country: 'गैबॉन',         capital: 'लिब्रेविल',    currency: 'फ्रैंक' },
  { country: 'कैमरून',        capital: 'याउंडे',       currency: 'फ्रैंक' },
  { country: 'मोजाम्बिक',     capital: 'मापुटो',       currency: 'मेटिकल' },
  { country: 'जाम्बिया',      capital: 'लुसाका',       currency: 'क्वाचा' },
  { country: 'मेडागास्कर',    capital: 'अंटानानारिवो',  currency: 'अरियारी' },
  { country: 'रवांडा',        capital: 'किगाली',       currency: 'फ्रैंक' },
  { country: 'सेनेगल',        capital: 'डकार',         currency: 'फ्रैंक' },
  { country: 'माली',          capital: 'बमाको',        currency: 'फ्रैंक' },
  { country: 'सोमालिया',      capital: 'मोगादिशु',     currency: 'शिलिंग' },
  { country: 'अंगोला',        capital: 'लुआंडा',       currency: 'क्वान्ज़ा' },
];

// ─── 100 Important Days ──────────────────────────────────────────────────────
export const IMPORTANT_DAYS_DATA: DayEntry[] = [
  { date: '1 जनवरी',      event: 'विश्व नव वर्ष दिवस' },
  { date: '10 जनवरी',     event: 'विश्व हिन्दी दिवस' },
  { date: '12 जनवरी',     event: 'राष्ट्रीय युवा दिवस (स्वामी विवेकानंद जयंती)' },
  { date: '15 जनवरी',     event: 'थल सेना दिवस' },
  { date: '23 जनवरी',     event: 'नेताजी सुभाष चंद्र बोस जयंती' },
  { date: '24 जनवरी',     event: 'राष्ट्रीय बालिका दिवस' },
  { date: '25 जनवरी',     event: 'राष्ट्रीय मतदाता दिवस' },
  { date: '26 जनवरी',     event: 'गणतंत्र दिवस' },
  { date: '28 जनवरी',     event: 'डेटा संरक्षण दिवस' },
  { date: '30 जनवरी',     event: 'शहीद दिवस (महात्मा गाँधी पुण्यतिथि)' },
  { date: '4 फरवरी',      event: 'विश्व कैंसर दिवस' },
  { date: '12 फरवरी',     event: 'राष्ट्रीय उत्पादकता दिवस' },
  { date: '13 फरवरी',     event: 'सरोजिनी नायडू जयंती' },
  { date: '14 फरवरी',     event: 'वेलेंटाइन डे' },
  { date: '20 फरवरी',     event: 'विश्व सामाजिक न्याय दिवस' },
  { date: '21 फरवरी',     event: 'अंतरराष्ट्रीय मातृभाषा दिवस' },
  { date: '22 फरवरी',     event: 'विश्व स्काउट दिवस' },
  { date: '24 फरवरी',     event: 'केंद्रीय उत्पाद शुल्क दिवस' },
  { date: '28 फरवरी',     event: 'राष्ट्रीय विज्ञान दिवस' },
  { date: '1 मार्च',      event: 'विश्व नागरिक सुरक्षा दिवस' },
  { date: '3 मार्च',      event: 'विश्व वन्यजीव दिवस' },
  { date: '4 मार्च',      event: 'राष्ट्रीय सुरक्षा दिवस' },
  { date: '8 मार्च',      event: 'अंतरराष्ट्रीय महिला दिवस' },
  { date: '15 मार्च',     event: 'विश्व उपभोक्ता अधिकार दिवस' },
  { date: '20 मार्च',     event: 'विश्व गौरैया दिवस' },
  { date: '21 मार्च',     event: 'विश्व वन दिवस' },
  { date: '22 मार्च',     event: 'विश्व जल दिवस' },
  { date: '23 मार्च',     event: 'विश्व मौसम विज्ञान दिवस' },
  { date: '24 मार्च',     event: 'विश्व टीबी दिवस' },
  { date: '25 मार्च',     event: 'गणेश शंकर विद्यार्थी बलिदान दिवस' },
  { date: '27 मार्च',     event: 'विश्व रंगमंच दिवस' },
  { date: '1 अप्रैल',     event: 'उड़ीसा स्थापना दिवस' },
  { date: '2 अप्रैल',     event: 'विश्व ऑटिज्म जागरूकता दिवस' },
  { date: '5 अप्रैल',     event: 'राष्ट्रीय समुद्री दिवस' },
  { date: '7 अप्रैल',     event: 'विश्व स्वास्थ्य दिवस' },
  { date: '10 अप्रैल',    event: 'विश्व होम्योपैथी दिवस' },
  { date: '11 अप्रैल',    event: 'राष्ट्रीय सुरक्षित मातृत्व दिवस' },
  { date: '13 अप्रैल',    event: 'जलियाँवाला बाग हत्याकांड स्मृति दिवस' },
  { date: '14 अप्रैल',    event: 'डॉ. भीमराव अंबेडकर जयंती' },
  { date: '17 अप्रैल',    event: 'विश्व हीमोफीलिया दिवस' },
  { date: '18 अप्रैल',    event: 'विश्व विरासत दिवस' },
  { date: '21 अप्रैल',    event: 'राष्ट्रीय सिविल सेवा दिवस' },
  { date: '22 अप्रैल',    event: 'पृथ्वी दिवस' },
  { date: '23 अप्रैल',    event: 'विश्व पुस्तक एवं कॉपीराइट दिवस' },
  { date: '24 अप्रैल',    event: 'राष्ट्रीय पंचायती राज दिवस' },
  { date: '29 अप्रैल',    event: 'अंतरराष्ट्रीय नृत्य दिवस' },
  { date: '1 मई',         event: 'अंतरराष्ट्रीय श्रम दिवस' },
  { date: '3 मई',         event: 'विश्व प्रेस स्वतंत्रता दिवस' },
  { date: '7 मई',         event: 'रवींद्रनाथ टैगोर जयंती' },
  { date: '8 मई',         event: 'विश्व रेड क्रॉस दिवस' },
  { date: '11 मई',        event: 'राष्ट्रीय प्रौद्योगिकी दिवस' },
  { date: '12 मई',        event: 'अंतरराष्ट्रीय नर्स दिवस' },
  { date: '15 मई',        event: 'अंतरराष्ट्रीय परिवार दिवस' },
  { date: '17 मई',        event: 'विश्व दूरसंचार दिवस' },
  { date: '18 मई',        event: 'विश्व संग्रहालय दिवस' },
  { date: '21 मई',        event: 'राष्ट्रीय आतंकवाद विरोधी दिवस' },
  { date: '22 मई',        event: 'अंतरराष्ट्रीय जैव विविधता दिवस' },
  { date: '24 मई',        event: 'राष्ट्रमंडल दिवस' },
  { date: '31 मई',        event: 'विश्व तंबाकू निषेध दिवस' },
  { date: '4 जून',        event: 'अंतरराष्ट्रीय बाल दिवस' },
  { date: '5 जून',        event: 'विश्व पर्यावरण दिवस' },
  { date: '8 जून',        event: 'विश्व महासागर दिवस' },
  { date: '12 जून',       event: 'विश्व बाल श्रम निषेध दिवस' },
  { date: '14 जून',       event: 'विश्व रक्तदान दिवस' },
  { date: '21 जून',       event: 'अंतरराष्ट्रीय योग दिवस' },
  { date: '23 जून',       event: 'संयुक्त राष्ट्र लोक सेवा दिवस' },
  { date: '26 जून',       event: 'अंतरराष्ट्रीय नशा निरोधक दिवस' },
  { date: '29 जून',       event: 'राष्ट्रीय सांख्यिकी दिवस' },
  { date: '1 जुलाई',      event: 'राष्ट्रीय चिकित्सक दिवस' },
  { date: '11 जुलाई',     event: 'विश्व जनसंख्या दिवस' },
  { date: '18 जुलाई',     event: 'नेल्सन मंडेला अंतरराष्ट्रीय दिवस' },
  { date: '26 जुलाई',     event: 'कारगिल विजय दिवस' },
  { date: '28 जुलाई',     event: 'विश्व हेपेटाइटिस दिवस' },
  { date: '6 अगस्त',      event: 'हिरोशिमा दिवस' },
  { date: '9 अगस्त',      event: 'विश्व आदिवासी दिवस' },
  { date: '12 अगस्त',     event: 'अंतरराष्ट्रीय युवा दिवस' },
  { date: '15 अगस्त',     event: 'स्वतंत्रता दिवस' },
  { date: '20 अगस्त',     event: 'सद्भावना दिवस (राजीव गाँधी जयंती)' },
  { date: '29 अगस्त',     event: 'राष्ट्रीय खेल दिवस (ध्यानचंद जयंती)' },
  { date: '5 सितंबर',     event: 'शिक्षक दिवस (डॉ. राधाकृष्णन जयंती)' },
  { date: '8 सितंबर',     event: 'अंतरराष्ट्रीय साक्षरता दिवस' },
  { date: '14 सितंबर',    event: 'हिन्दी दिवस' },
  { date: '15 सितंबर',    event: 'अभियंता दिवस' },
  { date: '16 सितंबर',    event: 'विश्व ओजोन दिवस' },
  { date: '21 सितंबर',    event: 'अंतरराष्ट्रीय शांति दिवस' },
  { date: '22 सितंबर',    event: 'विश्व गैंडा दिवस' },
  { date: '26 सितंबर',    event: 'विश्व पर्यावरण स्वास्थ्य दिवस' },
  { date: '27 सितंबर',    event: 'विश्व पर्यटन दिवस' },
  { date: '1 अक्टूबर',    event: 'अंतरराष्ट्रीय वृद्ध जन दिवस' },
  { date: '2 अक्टूबर',    event: 'गाँधी जयंती / अंतरराष्ट्रीय अहिंसा दिवस' },
  { date: '4 अक्टूबर',    event: 'विश्व पशु कल्याण दिवस' },
  { date: '5 अक्टूबर',    event: 'विश्व शिक्षक दिवस' },
  { date: '8 अक्टूबर',    event: 'भारतीय वायु सेना दिवस' },
  { date: '9 अक्टूबर',    event: 'विश्व डाक दिवस' },
  { date: '10 अक्टूबर',   event: 'विश्व मानसिक स्वास्थ्य दिवस' },
  { date: '14 अक्टूबर',   event: 'विश्व मानक दिवस' },
  { date: '16 अक्टूबर',   event: 'विश्व खाद्य दिवस' },
  { date: '24 अक्टूबर',   event: 'संयुक्त राष्ट्र दिवस' },
  { date: '31 अक्टूबर',   event: 'राष्ट्रीय एकता दिवस (सरदार पटेल जयंती)' },
  { date: '4 नवंबर',      event: 'कार्बन कॉपी दिवस' },
  { date: '7 नवंबर',      event: 'शिशु सुरक्षा दिवस' },
  { date: '9 नवंबर',      event: 'विश्व सेवा दिवस' },
  { date: '11 नवंबर',     event: 'राष्ट्रीय शिक्षा दिवस (मौलाना आजाद जयंती)' },
  { date: '14 नवंबर',     event: 'बाल दिवस (नेहरू जयंती) / विश्व मधुमेह दिवस' },
  { date: '17 नवंबर',     event: 'अंतरराष्ट्रीय छात्र दिवस' },
  { date: '19 नवंबर',     event: 'विश्व शौचालय दिवस' },
  { date: '21 नवंबर',     event: 'विश्व टेलीविजन दिवस' },
  { date: '26 नवंबर',     event: 'संविधान दिवस (संविधान अंगीकरण दिवस)' },
  { date: '1 दिसंबर',     event: 'विश्व एड्स दिवस' },
  { date: '3 दिसंबर',     event: 'विश्व विकलांगता दिवस' },
  { date: '4 दिसंबर',     event: 'भारतीय नौसेना दिवस' },
  { date: '5 दिसंबर',     event: 'विश्व मृदा दिवस' },
  { date: '7 दिसंबर',     event: 'भारतीय सशस्त्र सेना झंडा दिवस' },
  { date: '10 दिसंबर',    event: 'अंतरराष्ट्रीय मानवाधिकार दिवस' },
  { date: '11 दिसंबर',    event: 'अंतरराष्ट्रीय पर्वत दिवस' },
  { date: '14 दिसंबर',    event: 'राष्ट्रीय ऊर्जा संरक्षण दिवस' },
  { date: '16 दिसंबर',    event: 'विजय दिवस (बांग्लादेश मुक्ति)' },
  { date: '18 दिसंबर',    event: 'अंतरराष्ट्रीय प्रवासी दिवस' },
  { date: '22 दिसंबर',    event: 'राष्ट्रीय गणित दिवस (रामानुजन जयंती)' },
  { date: '23 दिसंबर',    event: 'किसान दिवस (चौधरी चरण सिंह जयंती)' },
  { date: '24 दिसंबर',    event: 'राष्ट्रीय उपभोक्ता दिवस' },
  { date: '25 दिसंबर',    event: 'क्रिसमस दिवस / सुशासन दिवस (वाजपेयी जयंती)' },
];

// ─── 36 State Symbols (all Indian states) ────────────────────────────────────
export const STATE_SYMBOLS_DATA: StateSymbolEntry[] = [
  { state: 'उत्तर प्रदेश',    animal: 'बारहसिंगा',  bird: 'सारस (क्रौंच)',  flower: 'पलाश',         tree: 'अशोक' },
  { state: 'महाराष्ट्र',      animal: 'विशालकाय गिलहरी', bird: 'हरित कबूतर', flower: 'जारुल',       tree: 'आम' },
  { state: 'राजस्थान',        animal: 'ऊँट',          bird: 'गोडावण',        flower: 'रोहिड़ा',      tree: 'खेजड़ी' },
  { state: 'मध्य प्रदेश',     animal: 'बारहसिंगा',   bird: 'दूधराज (शाह बुलबुल)', flower: 'सफेद लिली', tree: 'बरगद' },
  { state: 'बिहार',           animal: 'गौर (बाइसन)',  bird: 'घरेलू गौरैया',  flower: 'कचनार',       tree: 'पीपल' },
  { state: 'गुजरात',          animal: 'एशियाई सिंह',  bird: 'राजहंस (फ्लेमिंगो)', flower: 'मेरीगोल्ड', tree: 'बरगद' },
  { state: 'पश्चिम बंगाल',    animal: 'मत्स्य बिल्ली', bird: 'श्वेत कंठ पक्षी', flower: 'नाइट जैस्मीन', tree: 'छातिम' },
  { state: 'तमिलनाडु',        animal: 'नीलगिरि तहर',  bird: 'पन्ना कबूतर',   flower: 'ग्लोरी लिली', tree: 'ताड़' },
  { state: 'कर्नाटक',         animal: 'भारतीय हाथी',  bird: 'नीलकंठ',        flower: 'कमल',          tree: 'चंदन' },
  { state: 'आंध्र प्रदेश',    animal: 'चिंकारा हिरण', bird: 'नीलकंठ',        flower: 'कुमुद',        tree: 'नीम' },
  { state: 'तेलंगाना',        animal: 'चीतल',          bird: 'पालपिट्टा',     flower: 'तांगेडु',      tree: 'जम्मी चेट्टु' },
  { state: 'केरल',            animal: 'भारतीय हाथी',  bird: 'ग्रेट हॉर्नबिल', flower: 'अमलतास',      tree: 'नारियल' },
  { state: 'ओड़िशा',          animal: 'सांभर',         bird: 'भारतीय रोलर',   flower: 'अशोक',         tree: 'अश्वत्थ' },
  { state: 'पंजाब',           animal: 'काला हिरन',     bird: 'बाज',           flower: 'ग्लेडियोलस',   tree: 'शीशम' },
  { state: 'हरियाणा',         animal: 'काला हिरन',     bird: 'काला तीतर',     flower: 'कमल',          tree: 'पीपल' },
  { state: 'हिमाचल प्रदेश',   animal: 'हिम तेंदुआ',   bird: 'पश्चिमी ट्रैगोपन', flower: 'गुलाबी रोडोडेंड्रोन', tree: 'देवदार' },
  { state: 'उत्तराखंड',       animal: 'कस्तूरी मृग',  bird: 'मोनाल',         flower: 'ब्रह्म कमल',   tree: 'बुरांश' },
  { state: 'झारखंड',          animal: 'हाथी',          bird: 'कोयल',          flower: 'पलाश',         tree: 'साल' },
  { state: 'छत्तीसगढ़',       animal: 'जंगली भैंसा',  bird: 'पहाड़ी मैना',   flower: 'गेंदा',        tree: 'साल' },
  { state: 'असम',             animal: 'एक सींग वाला गैंडा', bird: 'व्हाइट विंग्ड वुड डक', flower: 'द्रौपदी माला', tree: 'होलोंग' },
  { state: 'अरुणाचल प्रदेश',  animal: 'मिथुन',         bird: 'ग्रेट हॉर्नबिल', flower: 'फॉक्सटेल ऑर्किड', tree: 'होलोंग' },
  { state: 'मणिपुर',          animal: 'संगाई हिरन',   bird: 'मिसेज ह्यूम तीतर', flower: 'सिरोही लिली', tree: 'तुन' },
  { state: 'मेघालय',          animal: 'क्लाउडेड तेंदुआ', bird: 'पहाड़ी मैना', flower: 'सोनहारी', tree: 'गमारी' },
  { state: 'मिजोरम',          animal: 'सेरो',          bird: 'ह्यूम तीतर',    flower: 'रेड वेंडा',    tree: 'नागकेसर' },
  { state: 'नागालैंड',        animal: 'मिथुन',         bird: 'ब्लिथ ट्रेगोपन', flower: 'रोडोडेंड्रोन', tree: 'एल्डर' },
  { state: 'त्रिपुरा',        animal: 'फायर (पिड्डा)',  bird: 'ग्रीन इंपीरियल पिजन', flower: 'नाग केसर', tree: 'आगर' },
  { state: 'सिक्किम',         animal: 'लाल पांडा',     bird: 'ब्लड फेज़ेंट',   flower: 'नोबल ऑर्किड', tree: 'रोडोडेंड्रोन' },
  { state: 'गोवा',            animal: 'गौर',           bird: 'फ्लेम-थ्रोटेड बुलबुल', flower: 'प्लूमेरिया', tree: 'अत्ती' },
  { state: 'जम्मू कश्मीर',    animal: 'हंगुल (कश्मीर हिरन)', bird: 'काला गर्दन वाली सारस', flower: 'कमल', tree: 'चिनार' },
];

// Generate all GS questions from compact data
export function getAllGeneratedGSQuestions(): GSQuestion[] {
  const worldGK = generateWorldGK(COUNTRY_DATA) as GSQuestion[];
  const days = generateImportantDays(IMPORTANT_DAYS_DATA) as GSQuestion[];
  const symbols = generateStateSymbols(STATE_SYMBOLS_DATA) as GSQuestion[];
  return [...worldGK, ...days, ...symbols];
}
